import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { changeDir, changeExists } from '../openspec-bridge.js';
import { parseScenarios } from '../bdd/linter.js';
import * as fm from '../frontmatter.js';

export async function runDecompose({ feature, force = false } = {}) {
  if (!feature) throw new Error('feature name is required');
  if (!changeExists(feature)) {
    const err = new Error(`OpenSpec change "${feature}" not found.`);
    err.remediation = `Run \`openspecpm propose ${feature}\` first.`;
    throw err;
  }

  const dir = changeDir(feature);
  const proposalPath = join(dir, 'proposal.md');
  const tasksPath = join(dir, 'tasks.md');

  let existingItems = [];
  if (existsSync(tasksPath)) {
    const raw = await readFile(tasksPath, 'utf8');
    const { data } = fm.parse(raw);
    existingItems = data.items ?? [];
    if (existingItems.length && !force) {
      process.stdout.write(`tasks.md already has ${existingItems.length} item(s). Pass --force to merge.\n`);
      return;
    }
  }

  const proposal = existsSync(proposalPath) ? await readFile(proposalPath, 'utf8') : '';
  const specsItems = await extractFromSpecs(dir);
  const proposalItems = extractFromProposal(proposal);
  const merged = dedupe([...existingItems, ...proposalItems, ...specsItems]);

  const out = fm.serialize(
    { schema_version: 1, items: merged },
    `\n# Tasks\n\nGenerated by \`openspecpm decompose\`. Refine titles, set depends_on, mark parallel: true where safe.\n`,
  );
  await writeFile(tasksPath, out, 'utf8');
  process.stdout.write(`✓ Wrote ${merged.length} task(s) to ${tasksPath}.\n`);
  if (proposalItems.length) process.stdout.write(`  ${proposalItems.length} from proposal headings/checklists.\n`);
  if (specsItems.length) process.stdout.write(`  ${specsItems.length} from BDD scenarios in specs/.\n`);
  process.stdout.write(`Next: review tasks.md, then \`openspecpm sync ${feature}\`.\n`);
}

function extractFromProposal(md) {
  if (!md) return [];
  const { body } = fm.parse(md);
  const items = [];
  let inTasksSection = false;
  for (const raw of body.split(/\r?\n/)) {
    const line = raw.trim();
    if (/^#+\s*(tasks|implementation|deliverables|steps)/i.test(line)) {
      inTasksSection = true;
      continue;
    }
    if (/^#+\s/.test(line)) inTasksSection = false;
    const check = line.match(/^-\s*\[( |x|X)\]\s+(.+)/);
    if (check) {
      items.push({ title: check[2].trim(), sync_state: 'pending', parallel: false, depends_on: [] });
      continue;
    }
    if (inTasksSection) {
      const bullet = line.match(/^[-*]\s+(.+)/);
      const numbered = line.match(/^\d+[.)]\s+(.+)/);
      const match = bullet ?? numbered;
      if (match) items.push({ title: match[1].trim(), sync_state: 'pending', parallel: false, depends_on: [] });
    }
  }
  return items;
}

async function extractFromSpecs(featureDir) {
  const specsDir = join(featureDir, 'specs');
  if (!existsSync(specsDir)) return [];
  const { readdir } = await import('node:fs/promises');
  const files = await readdir(specsDir);
  const items = [];
  for (const f of files) {
    if (!f.endsWith('.md')) continue;
    const raw = await readFile(join(specsDir, f), 'utf8');
    for (const scenario of parseScenarios(raw)) {
      items.push({
        title: `Implement: ${scenario.title}`,
        sync_state: 'pending',
        parallel: false,
        depends_on: [],
        spec: f,
      });
    }
  }
  return items;
}

function dedupe(items) {
  const seen = new Set();
  const out = [];
  for (const item of items) {
    const key = (item.title ?? '').trim().toLowerCase();
    if (!key || seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}
